name: Changelog

on:
  pull_request:

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Verify changes in Changelog
        run: git diff main -- CHANGELOG.md | grep ""
